### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G2#11]
Who is going to do task 3? We can discuss on how to proceed.

**Comment by AhmedCode99** [comment]
@tirthbha is doing it

**Comment by reshnashrestha** [comment]
@tirthbha have you started doing it ?
How are you planning to do the comparison?
In task 3, there is a task:

Compare the numpy integration functions to the ones found in compphys
So what really are we comparing? Can you elaborate?

**Comment by tirthbha** [comment]
@reshnashrestha Have you done the task1 and task2?

**Comment by reshnashrestha** [comment]
I overviewed the task. Group members are working on it. I have generated the library with all functions. Surgically I think that task 3 can be done to some extent without huge dependency in other tasks so if it’s possible we can proceed. Have you started?

**Comment by tirthbha** [comment]
@reshnashrestha I am trying to figure out the issue that I encountered for the integral calculation, which is as follows:
Although I handled the singularity at x=0 for the functions: exp(-1\x)[return np.where(x != 0, np.exp(-1/x), 0)] and cos(1/x) [return np.where(x !=0, np.cos(1/x),0)]
 I am getting the warning
"RuntimeWarning: divide by zero encountered in divide  
How have you handled this issue in your case?

**Comment by tirthbha** [comment]
@reshnashrestha We can find out the roots by using simplest method like Bisection  method and Newton-Raphson method, right?

**Comment by reshnashrestha** [comment]
You are right. Which methods do you adopted? Are they working? Do we need to make any changes?

**Comment by tirthbha** [comment]
@reshnashrestha Yes both are working efficiently.

**Comment by reshnashrestha** [comment]
That’s great.

**Comment by reshnashrestha** [comment]
What is your update on task 3

**Comment by tirthbha** [comment]
@reshnashrestha Are we supposed to compare the results obtained from the three methods ( in task1) with those obtained from numpy integration?

**Comment by tirthbha** [comment]
@reshnashrestha Have you done first point of task 3?

**Comment by AhmedCode99** [comment]
Do you need any help?

**Comment by tirthbha** [comment]
Everything is well now!
