### ISSUE TITLE
Number of subintervals

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G2#15]
Hi all,
For using Sympson's and Trapezoidal method we have to define the number of subinterval. For this we define the function as "def simpson(f, a, b, n)" , what is the value of n (number of subintervals ) to be used to calculate and plot the integration here?

**Comment by AhmedCode99** [comment]
That is up to you, the more intervals you have the more accurate your answer will be. But your code will take longer to run

**Comment by pratibha77118** [comment]
@AhmedCode99 thanks for the answer.

**Comment by AhmedCode99** [comment]
You're welcome
