### ISSUE TITLE
Is a whole folder necessary for a single-file library?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework6G2#17]
Online sources (such as https://packaging.python.org/en/latest/tutorials/packaging-projects/) tell me that when creating a python library, you need to create a folder with the python files you wish to include and an init.py file. However, for a single file this leads to the slightly redundant behavior I noted in this issue https://github.com/ubsuny/23-Homework6G1/issues/17.

My point is, do we need to do the whole folder setup, or are we able to just use a single file in this case?

**Comment by tirthbha** [comment]
@WildJimmy Yes we have a single python file, so it's not necessary to create a folder for a single file, I guess.

**Comment by reshnashrestha** [comment]
If you want to you can but it doe not seem like mandatory.

**Comment by AhmedCode99** [comment]
It is not required
