### ISSUE TITLE
Numpy Integration and Comphys integration

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G2#18]
In task 3, there is a task:

Compare the numpy integration functions to the ones found in compphys
So what really are we comparing? Can you elaborate?

**Comment by tirthbha** [comment]
@reshnashrestha I am also doing task 3, however unable to figure out this task me too.

**Comment by reshnashrestha** [comment]
Okay we can discuss this tomorrow in the class with professor

**Comment by tirthbha** [comment]
Sure!

**Comment by AhmedCode99** [comment]
Compare compphys with built-in python functions like:

https://numpy.org/doc/stable/reference/generated/numpy.trapz.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simpson.html
