### ISSUE TITLE
Comphys integration

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G2#19]
What does this mean?

**Comment by tirthbha** [comment]
@reshnashrestha I have the the same question.

**Comment by reshnashrestha** [comment]
Have you figured out?

**Comment by AhmedCode99** [comment]
Compare compphys with built-in python functions like:

https://numpy.org/doc/stable/reference/generated/numpy.trapz.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simpson.html
