### ISSUE TITLE
Numpy integration

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G2#20]
What are these?

**Comment by tirthbha** [comment]
@reshnashrestha I have the same question.

**Comment by tirthbha** [comment]
@reshnashrestha sure

**Comment by AhmedCode99** [comment]
Compare compphys with built-in python functions like:

https://numpy.org/doc/stable/reference/generated/numpy.trapz.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simpson.html
