### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G2#22]
Do we need to use all the functions listed on the task 1 with the three different approaches? 
Have you done task1 @AhmedCode99 or how far have you done?

**Comment by Mosaddeq107** [comment]
> Do we need to use all the functions listed on the task 1 with the three different approaches? Have you done task1 @AhmedCode99 or how far have you done?

You need to use all three functions that are mentioned in task 1.

**Comment by AhmedCode99** [comment]
true
