### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G2#29]
@AhmedCode99 @LinxuanHu There is no documentation part in task 3. I think, we should make documentation for own task  by ourselves.

**Comment by poojashresthacode** [comment]
Yeah, you are right @tirthbha

**Comment by Mosaddeq107** [comment]
> @AhmedCode99 @LinxuanHu There is no documentation part in task 3. I think, we should make documentation for own task by ourselves.

I'm confused about that. Did Dr. Tim say that?

**Comment by Mosaddeq107** [comment]
> Yeah, you are right @tirthbha

I may have missed it, but did Prof mention it?

**Comment by AhmedCode99** [comment]
That is not required

**Comment by tirthbha** [comment]
I have done my part and sent @AhmedCode99 pull requests, please accept those.
Thank you!
