### ISSUE TITLE
Add labels

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G2#30]
@AhmedCode99 Can you please add some more new labels?

**Comment by AhmedCode99** [comment]
Do you have some labels in mind? Because it feels like we have enough

**Comment by reshnashrestha** [comment]
We are using task specific labels. Some useful labels could be update, progress, essential, attention, helpful, and so on.

**Comment by tirthbha** [comment]
@AhmedCode99 yes add some specific labels like task1, task2, task3.

**Comment by AhmedCode99** [comment]
We had those since like day 2
