### ISSUE TITLE
Generating calculus.py

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework6G2#31]
Hi folks, 
Do we need to include all the functions from Task 1 and Task 2 in **calculus.py**?

**Comment by tirthbha** [comment]
@Mosaddeq107 I did that which is still in pending to be accepted by the maintainer.

**Comment by Mosaddeq107** [comment]
> @Mosaddeq107 I did that which is still in pending to be accepted by the maintainer.

Now, your request has been accepted.

**Comment by Mosaddeq107** [comment]
Thanks for your suggestions

**Comment by AhmedCode99** [comment]
cool
