### ISSUE TITLE
compare accuracies in task 2

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework6G2#32]
How did you compare accuracies in task 2? Do we have to compare the simple roots function with outputs of other functions or use the accurate value to compare?

**Comment by tirthbha** [comment]
@s4il3sh Which method have you used to find roots?

**Comment by s4il3sh** [comment]
I am planning to use root_simple and root_tangent functions. Which task are you doing?

**Comment by reshnashrestha** [comment]
Aren't we suppose to implement all functions provided in the comphys [rootfinding.py](https://github.com/ubsuny/CompPhys/blob/main/Calculus/rootfinding.py)

**Comment by tirthbha** [comment]
@s4il3sh root_tangent is more simplest form, however I got some error with root_simple function. Hope it will work in your case.

**Comment by tirthbha** [comment]
@reshnashrestha I think we need to choose any two of them.

**Comment by reshnashrestha** [comment]
Oh okay then.

**Comment by AhmedCode99** [comment]
Yes, I think we need to choose any two of them and plot the answer
