### ISSUE TITLE
Plots for task 1

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G2#34]
![plots_task1](https://github.com/ubsuny/23-Homework6G2/assets/143649367/c5c3d39d-0d45-43c1-9fcb-3c03774a173a)
Hope these graphs make sense.
In the last plot, constant=1/2, as our group number is 2.

**Comment by AhmedCode99** [comment]
Nice, check task1_simpson.ipynb, and tell me what you think
