### ISSUE TITLE
How are you going to plot the integrals?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework6G2#36]
If $\mathrm{F(x) =}\int_a^b \mathrm{f(x)}\mathrm{d}x$, how can you numerically obtain $F(x)$?

**Comment by AhmedCode99** [comment]
My idea is to calculate the integral from $a$ to $a + \epsilon$, where $\epsilon$ is a small number. Then keep repeating till I reach the upper bound $b$.

**Comment by AhmedCode99** [comment]
My first point is integral from $a$ to $a+\epsilon$
My second point is integral from $a$ to $a+2\epsilon$
My $n^{th}$ point is integral from $a$ to $a+n\epsilon$

**Comment by tirthbha** [comment]
@AhmedCode99 Plots are not for the integral, but for the functions. Just to be sure that functions are well defined or not within the given intervals.

**Comment by AhmedCode99** [comment]
@tirthbha you are wrong. Read the readme file on the main repo carefully

**Comment by tirthbha** [comment]
@AhmedCode99 The intention is to get rid from the zero divisor, right?

**Comment by AhmedCode99** [comment]
**Task 1:**
Use the four integral algorithms (Simpson, adaptive trapezoid, trapezoid) to create a Jupyter notebook that imports the functions from `calculus.py` and use them to calculate and **plot the integral** of:

**Comment by tirthbha** [comment]
> **Task 1:** Use the four integral algorithms (Simpson, adaptive trapezoid, trapezoid) to create a Jupyter notebook that imports the functions from `calculus.py` and use them to calculate and **plot the integral** of:

![Screenshot from 2023-11-20 13-28-42](https://github.com/ubsuny/23-Homework6G2/assets/143649367/c92d6e5a-d0b5-499a-b800-dd8c15fc168a)
![Screenshot from 2023-11-20 13-29-04](https://github.com/ubsuny/23-Homework6G2/assets/143649367/fc8a8a7e-8ff8-4c9f-aad9-f23308ababa2)
![Screenshot from 2023-11-20 13-30-01](https://github.com/ubsuny/23-Homework6G2/assets/143649367/7e40ee81-86c8-478b-85cb-50d4e8d05e78)

**Comment by AhmedCode99** [comment]
@tirthbha we are both right, Dr. Tim said we can do any

**Comment by tirthbha** [comment]
@AhmedCode99 Great!
