### ISSUE TITLE
Estimate efficiency for each method

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework6G2#38]
Hi all,
How have you calculated the efficiencies ( steps required to give the given accuracy) for each method. I compared the accuracies taking actual integration as a reference but I am confused what exactly mean the given accuracy to estimate the efficiencies of each method? If any one has completed this part, please share how to work on it?

**Comment by reshnashrestha** [comment]
@pratibha77118 have you figured this out?

**Comment by AhmedCode99** [comment]
Closed for inactivity, but feel free to reopen it
