### ISSUE TITLE
Which Functions are you using as numpy integrations?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G2#48]
I am asking for the task 3.

**Comment by reshnashrestha** [comment]
@tirthbha have you chosen any?

**Comment by tirthbha** [comment]
@reshnashrestha I have chosen numpy.trapz, numpy.simps, numpy.cumtrapz as the numpy functions for integration.

**Comment by AhmedCode99** [comment]
good luck to all
