### ISSUE TITLE
What is Group Number?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework6G2#5]
@laserlab In the integration limits, you mention a Group Number. Do you mean the homework group number?

**Comment by LinxuanHu** [comment]
yeah, i think we are 2

**Comment by LinxuanHu** [comment]
so in task 1, you will do x^3+1/2

**Comment by poojashresthacode** [comment]
Isn't it related to number of data groups rather than number of group members? or may be, i don't know, it is the number of group members, but can you explain what is the necessity to have the group number in the boundaries?

**Comment by AhmedCode99** [comment]
I guess it is just your homework group number
