### ISSUE TITLE
Problem in uploading files from google collab.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework6G2#58]
![image](https://github.com/ubsuny/23-Homework6G1/assets/143756553/57687f55-270f-4ca3-ba7e-1a0a99d3c452)
Hi, when I uploaded the file from google collab, it appears like this. The figure is overlapping with the code. How can I resolve it? Any solution will be highly appreciated.

**Comment by tirthbha** [comment]
@poojashresthacode Hope, it has been sorted out now.
