### ISSUE TITLE
What does the limit ]0,Pi] mean?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework6G2#6]
Does it mean $0 < x \leq \pi$?

**Comment by LinxuanHu** [comment]
i think it's same as (0,pi)

**Comment by tirthbha** [comment]
Actually, excluding 0 won't allow the function to give indeterminate form, I guess.

**Comment by poojashresthacode** [comment]
I think it is open interval notation

**Comment by poojashresthacode** [comment]
The reason why open interval notation is not written as (0, pi) is because this notation would be ambiguous. The parentheses could be interpreted as either open interval notation or as a function call. To avoid this ambiguity, the notation ]0, pi] is used to explicitly indicate that the interval is open.

**Comment by reshnashrestha** [comment]
]: The right square bracket ] indicates that the right endpoint is included in the interval.

0: This is the lower limit of the interval.

, (comma): The comma separates the lower and upper limits of the interval.

π * GroupNumber: This expression represents the upper limit of the interval. It is the product of the mathematical constant π (pi) and a variable or constant named GroupNumber.

]: The closing square bracket ] indicates that the upper limit is included in the interval.

Putting it together, ]0, π * GroupNumber] represents a right-open interval from 0 to π * GroupNumber. It includes all real numbers greater than 0 and less than or equal to π * GroupNumber. The lower bound is closed (included), and the upper bound is open (excluded).

For example, if GroupNumber is 2, the interval becomes ]0, 2π], including 0 but excluding 2π. If GroupNumber is 3, the interval becomes ]0, 3π], and so on.

**Comment by AhmedCode99** [comment]
That seems resonable
