### ISSUE TITLE
No docstrings in task1_calculus.py

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework6G2#76]
Hi @AhmedCode99,

I see that you have docstrings in your task3_calculus.py library, but not task1_calculus.py. I made a pull request (https://github.com/ubsuny/23-Homework6G2/pull/75) where I have added them to task1_calculus.py so that both are properly documented

**Comment by tirthbha** [comment]
@WildJimmy I am working on it in my own branch, now I have sent a merge request.

**Comment by WildJimmy** [comment]
I am confused, I already sent the merge request for this change before making this issue as referenced in the original comment. Just need the maintainer @AhmedCode99 to look it over, but I don't know why another merge request is necessary

**Comment by tirthbha** [comment]
@WildJimmy Actually, my job is to add docstrings the algorithm file ans I was working on it. I did all my job in my own  branch and sent all jobs together  as a merge request to the main branch. I was unaware of your contribution to that file. So..
